MB-51718: Fix name collision with offsetof
When compiling under MSVC 2017 with default compiler options, the
following error is seen during compilation if 'offsetof' is used on a
struct, where a variable exists with the same name:

    C:\Users\daver\repos\server\forestdb\src\hash.cc(176): error C2132: syntax error: unexpected identifier
    C:\Users\daver\repos\server\forestdb\src\hash.cc(176): note: offsetof has a builtin meaning; use /Zc:offsetof- to revert to old, non-conforming definition

This is the same issue reported at
https://developercommunity.visualstudio.com/t/offsetof-fails-when-used-with-alias-template/208697,
and highlights the workaround - passing '/Zc:offsetof-' to the compiler.

We indeed did this as part of tlm change "Add support for MSVC2017"
(e21739f) in 2018, which solved the issue.

However, fast-forward to now when upgrading folly to v2022.02.14.00,
and it turns out that the workaround causes a cryptic error in folly
Synchronized.h:

    folly.exploded\include\folly/Synchronized.h(1414): error C2131: expression did not evaluate to a constant
    folly.exploded\include\folly/Synchronized.h(1414): note: failure was caused by non-constant arguments or reference to a non-constant symbol
    folly.exploded\include\folly/Synchronized.h(1414): note: see usage of 'folly::Synchronized<Foo::State,std::mutex>::Simulacrum::mutex_'
    folly.exploded\include\folly/Synchronized.h(1410): note: while compiling class template member function 'SynchronizedType *folly::LockedPtr<SynchronizedType,folly::SynchronizedBase<folly::Synchronized<Foo::State,std::mutex>,folly::detail::SynchronizedMutexLevel::Unique>::LockPolicyExclusive>::parent(void) const'
            with
            [
                SynchronizedType=folly::Synchronized<Foo::State,std::mutex>
            ]
    folly.exploded\include\folly/Synchronized.h(1266): note: see reference to function template instantiation 'SynchronizedType *folly::LockedPtr<SynchronizedType,folly::SynchronizedBase<folly::Synchronized<Foo::State,std::mutex>,folly::detail::SynchronizedMutexLevel::Unique>::LockPolicyExclusive>::parent(void) const' being compiled
            with
            [
                SynchronizedType=folly::Synchronized<Foo::State,std::mutex>
            ]
    C:\Users\daver\repos\folly_syncho_test\folly_syncho_test.cpp(6): note: see reference to class template instantiation 'folly::LockedPtr<Subclass,folly::SynchronizedBase<Subclass,folly::detail::SynchronizedMutexLevel::Unique>::LockPolicyExclusive>' being compiled
            with
            [
                Subclass=folly::Synchronized<Foo::State,std::mutex>
            ]

Disabling the workaround (and using default, standards-conforming
version of offsetof) fixes this folly Synchronized error.

As such, fix the forestdb offsetof warnings without disabling the new
offsetof impl, by renaming any local variables which collide with
struct names. We can then remove the '/Zc:offsetof-' flag in tlm (and
continue the folly upgrade).

Change-Id: I71c6efaf85782f0fd6686dfce8d957f84e679c98
Reviewed-on: https://review.couchbase.org/c/forestdb/+/175283
Reviewed-by: Srinath Duvuru <srinath.duvuru@couchbase.com>
Tested-by: Build Bot <build@couchbase.com>
Well-Formed: Restriction Checker